
Program('synthetic',
        ['main.cc', 'single-factor.cc', 'Graph.cc', 'Query.cc'],
        LIBS='libdai',
        CPPPATH='libdai/include/', LIBPATH='libdai/lib')

Command(['result_dyn_threshold_known.data',
         'result_dyn_threshold_novel.data',
         'result_fix_threshold_known.data',
         'result_fix_threshold_novel.data'], 'synthetic',
         './synthetic', chdir=1)

x = PDF('plot.pdf', 'plot.tex')
Depends(x, ['result_dyn_threshold_known.data',
            'result_dyn_threshold_novel.data',
            'result_fix_threshold_known.data',
            'result_fix_threshold_novel.data']);
