x = PDF('abstract.pdf', 'abstract.tex')
x = PDF('article.pdf', 'article.tex')
Depends(x, ['llncs.cls', 'refs.bib'])

Command('figures/roc-simple.pdf', '../semisupervised/dora-data/roc-simple.pdf', 'cp $SOURCE $TARGET')

SVGS = """
""".split()

for SVG in SVGS:
  base = SVG[0:-4]
  x = Command(base + '.pdf', base +'.svg', 'convert `basename ' +base+'.svg` `basename ' + base + '.pdf`', chdir=1)

