Command('NoveltyDetection.pdf', 'NoveltyDetection.svg', 'inkscape $SOURCE --export-pdf=$TARGET')
Command('place_classification.pdf', 'place_classification.svg', 'inkscape $SOURCE --export-pdf=$TARGET')
Command('RobotLayers.pdf', 'RobotLayers.svg', 'inkscape $SOURCE --export-pdf=$TARGET')
