Command('NoveltyDetection.pdf', 'NoveltyDetection.svg', 'convert $SOURCE $TARGET')
Command('place_classification.pdf', 'place_classification.svg', 'convert $SOURCE $TARGET')
Command('RobotLayers.pdf', 'RobotLayers.svg', 'convert $SOURCE $TARGET')
