
c = Command(['density_threshold.tex',
         'semi_threshold.tex',
         'explain.tex'],
         ['run.py',
          'explain.py',
          '#build/scripts/'
         ],
         'PYTHONPATH=$PYTHONPATH python $SOURCE.abspath',
         PYTHONPATH=Dir('#scripts').abspath,
         chdir=1)
