SConscript('synthetic/SConscript')

summary = PDF('summary-en.pdf', 'summary-en.tex')
Depends(summary, ['results/synthetic-all.pdf', 'tkz-base.sty', 'tkz-arith.sty', 'macros.tex'])
summary_pt = PDF('summary-pt.pdf', 'summary-pt.tex')
Depends(summary_pt, ['results/synthetic-all.pdf', 'tkz-base.sty', 'tkz-arith.sty', 'macros.tex'])

thesis = PDF('thesis.pdf', 'thesis.tex')

Depends(thesis, ['feupteses.sty', 'mieicpatch.sty', 'tkz-base.sty', 'tkz-arith.sty', 'figures/feup-logo.pdf']
              + ['abstract.tex',
                 'acknows.tex',
                 'introduction.tex',
                 'background.tex',
                 'contents.tex',
                 'semantic-mapping.tex',
                 'novelty-intro.tex',
                 'refs.bib'])

SVGS = """
figures/sift/sift.svg
figures/graphical-models/BayesNet.svg
figures/graphical-models/FactorGraph.svg
figures/graphical-models/MarkovRandomField.svg
""".split() 


for SVG in SVGS:
  base = SVG[0:-4]
  x = Command(base + '.pdf', base +'.svg', 'inkscape `basename ' +base+'.svg` --export-pdf=`basename ' + base + '.pdf`', chdir=1)
  if SVG == 'figures/sift/sift.svg':
    Depends(x, """figures/sift/truck.jpg
                  figures/sift/train.jpg
                  figures/sift/frog.jpg
                  figures/sift/cup.jpg
                  figures/sift/annotated.jpg""".split())

# Copy data from semantic-nd article.
Command('results/synthetic-all.pdf', '../semantic-nd/results/synthetic-all.pdf', 'cp $SOURCE $TARGET')
Command('results/synthetic-3features.pdf', '../semantic-nd/results/synthetic-3features.pdf', 'cp $SOURCE $TARGET')
Command('results/synthetic-5features.pdf', '../semantic-nd/results/synthetic-5features.pdf', 'cp $SOURCE $TARGET')
Command('results/synthetic-10features.pdf', '../semantic-nd/results/synthetic-10features.pdf', 'cp $SOURCE $TARGET')
Command('results/synthetic-50features.pdf', '../semantic-nd/results/synthetic-50features.pdf', 'cp $SOURCE $TARGET')
#Command('results/ontology-explain.tex', '../semantic-nd/results/ontology-explain.tex', 'cp $SOURCE $TARGET')
Command('figures/processes.pdf', '../semantic-nd/figures/processes.pdf', 'cp $SOURCE $TARGET')
Command('figures/chaingraph.pdf', '../semantic-nd/figures/chaingraph.pdf', 'cp $SOURCE $TARGET')
Command('figures/spatial-knowledge-representation.pdf', '../pdis/techreport/figures/system-representation/structure.pdf', 'cp $SOURCE $TARGET')

