thesis = PDF('thesis.pdf', 'thesis.tex')

Depends(thesis, ['feupteses.sty', 'mieicpatch.sty', 'figures/feup-logo.pdf']
              + ['abstract.tex',
                 'acknows.tex',
                 'background.tex',
                 'contents.tex',
                 'novelty-intro.tex',
                 'novelty.tex',
                 'refs.bib'])

SVGS = """
figures/sift/sift.svg
figures/graphical-models/BayesNet.svg
figures/graphical-models/FactorGraph.svg
figures/graphical-models/MarkovRandomField.svg
""".split() 


for SVG in SVGS:
  base = SVG[0:-4]
  x = Command(base + '.pdf', base +'.svg', 'inkscape `basename ' +base+'.svg` --export-pdf=`basename ' + base + '.pdf`', chdir=1)
  if SVG == 'figures/sift/sift.svg':
    Depends(x, """figures/sift/truck.jpg
                  figures/sift/train.jpg
                  figures/sift/frog.jpg
                  figures/sift/cup.jpg
                  figures/sift/annotated.jpg""".split())

# Copy data from semantic-nd article.
Command('figures/simple-cond-graph.pdf', '../semantic-nd/figures/simple-cond-graph.pdf', 'cp $SOURCE $TARGET')
Command('figures/simple-uniform-graph.pdf', '../semantic-nd/figures/simple-uniform-graph.pdf', 'cp $SOURCE $TARGET')
Command('figures/simple-independent-graph.pdf', '../semantic-nd/figures/simple-independent-graph.pdf', 'cp $SOURCE $TARGET')
Command('results/synthetic-all.pdf', '../semantic-nd/results/synthetic-all.pdf', 'cp $SOURCE $TARGET')
Command('results/synthetic-3features.pdf', '../semantic-nd/results/synthetic-3features.pdf', 'cp $SOURCE $TARGET')
Command('results/synthetic-5features.pdf', '../semantic-nd/results/synthetic-5features.pdf', 'cp $SOURCE $TARGET')
Command('results/synthetic-10features.pdf', '../semantic-nd/results/synthetic-10features.pdf', 'cp $SOURCE $TARGET')
Command('results/synthetic-50features.pdf', '../semantic-nd/results/synthetic-50features.pdf', 'cp $SOURCE $TARGET')

